baseurl:   /steam-condenser
markdown:  redcarpet
permalink: pretty
pygments:  true
exclude:   [README.md,bower.json,_bower_components]

# Site Content Vars.
headerNav:
 - name: Installation
   url:  install
 - name: Usage
   url:  usage
 - name: Contribute
   url:  contribute
 - name: License
   url:  license

scVersions:
    java: 1.3.4
    php:  1.3.4
    ruby: 1.3.5
